apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: inception-of-things
  labels:
    app: app1
  annotations:
    description: "Deployment of app1 - a simple hello, world"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1-container
        image: hashicorp/http-echo:latest
        args:
        - "-text=Hello from app1"
        imagePullPolicy: IfNotPresent
        # Ports
        ports:
        - name: http
          protocol: TCP
          containerPort: 5678
        # Resources usage
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        # HealthCheck
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: inception-of-things
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678