apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.192.168.56.110.nip.io/root/webapp.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10

---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://gitlab.192.168.56.110.nip.io/root/webapp.git
  username: ngalzand
  insecure: "true"